AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  audioHandler:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: audioHandler
      Handler: audioHandler.audioHandler
      Runtime: nodejs18.x
      CodeUri: ./handlers
      # Environment:
      #   Variables:
      #     GREETINGS_TABLE: !Ref GreetingsTable
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref transpileAudio
        - LambdaInvokePolicy:
            FunctionName: !Ref readS3File
        - LambdaInvokePolicy:
            FunctionName: !Ref textTranslation
      Events:
        Api:
          Type: Api
          Properties:
            Path: /upload-audio
            Method: GET
  transpileAudio:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: transpileAudio
      Handler: transpileAudio.transpileAudio
      Runtime: nodejs18.x
      CodeUri: ./services
  readS3File:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: readS3File
      Handler: readS3File.readS3File
      Runtime: nodejs18.x
      CodeUri: ./services
      Policies:
        - S3ReadPolicy:
            BucketName: ada-transcript-out
  textTranslation:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: textTranslation
      Handler: textTranslation.textTranslation
      Runtime: nodejs18.x
      CodeUri: ./services
Outputs:
  MyApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload-audio/"
